parameters:
#    sopinet_timeline.example.class: Sopinet\TimelineBundle\Example

services:
#    sopinet_timeline.example:
#        class: %sopinet_timeline.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
